### ISSUE TITLE
Error report has no state

### ISSUE THREAD

**Issue by vinnymac** [skiano/react-safe-render#1]
I noticed that `react-safe-render` exposes some parts of the component such as `displayName`, `props`, and the lifecycle method that threw the error. Is their a reason the `state` isn't exposed as well? Why not expose the component itself in the report?

An additional benefit other than your entire tree not getting locked up is that you can now reveal exactly which components in your app are failing and what state they were in when they failed. It would be useful to have as much information as possible. Thoughts?

**Comment by zincli** [comment]
@vinnymac maybe their components are mostly dump components which only having props.

**Comment by lenards** [comment]
_(wild speculation ...)_
Exposing `state` might be as simple as altered the `wrap` function to include it in `report` [here](https://github.com/skiano/react-safe-render/blob/master/index.js#L51). 

I'm in the middle of using/adopting this for logging exceptions via "raven-js" to Sentry, so I'll see if I toss a breakpoint into `wrap` and inspect that's present at the time of the `report` initializing.

**Comment by vinnymac** [comment]
@lenards I too am using this to log with `raven-js` to Sentry. Modifying this to report the `state` should not be difficult, I was just wondering if the creator intentionally left it out for a reason. If you have success with it, be sure to let me know!

**Comment by skiano** [comment]
I did not leave it out for any particular reason. I just haven't invested any time in it, because Facebook has been promising a library fix for this for a long time. If anyone wants to add it I think it sounds like a good idea!

**Comment by vinnymac** [comment]
@skiano awesome! I am looking forward to Facebook coming out with an official solution as well.

Would this solution suffice for most people?

Change this [line](https://github.com/skiano/react-safe-render/blob/master/index.js#L51) to be

``` javascript
component : this,
```

Then we should be able to access `state` and `props` as necessary.

**Comment by skiano** [comment]
i think it would be better to add state as a key rather than turning over all of "this". Because there's so much in "this" and who knows what people would start depending on that isn't covered in the tests

**Comment by skiano** [comment]
also for reference

this is the thread that has been going about this:
https://github.com/facebook/react/issues/2461

it's been on their radar for quite a while

**Comment by vinnymac** [comment]
Good point, well in that case, we should just do

``` javascript
state : this.state,
```

It looks like some progress is being made, but at least we have this lib in the meantime thanks to you.

**Comment by lenards** [comment]
I agree with @skiano - I'd cite something like "principle of least authority" for not handing over `this` and scope to `this.state` (not that devising a position is really needed). 

Thank you Greg for the library. I'll see if I can get a PR put together & submitted.
